### ISSUE TITLE
my question about ABE

### ISSUE THREAD

**Issue by exmarine** [fentec-project/CiFEr#21]
Please forgive me for my poor English.I am a student in Asian.
How can I get character string from FP12_BN254 ?
I use the function "extern void FP12_BN254_toOctet(octet *S,FP12_BN254 *x);".
But I cannot get the character string what I use the function'extern void FP12_BN254_fromOctet(FP12_BN254 *x,octet *S);' to input.

**Comment by tilenmarc** [comment]
Hi,
the function you mention and the structs octet and FP12_BN254 are part of AMCL library that we are using in our ABE schemes.
The function `FP12_BN254_fromOctet(FP12_BN254 *x,octet *S)` is the right choice, since it saves an element `x` of `FP12_BN254` to `octet` `S`. Now you have to understand how `octet` is defined:
`typedef struct
{
    int len;   /**< length in bytes  */
    int max;   /**< max length allowed - enforce truncation  */
    char *val; /**< byte array  */
} octet;`
This means that if you want a string out of `octet` `S`, you have to call `S.val` (this is a string of length `S.len`).
Hope this helps.
Kind regards,
Tilen

**Comment by tilenmarc** [comment]
I am closing the issue since I believe it was answered and there is no additional questions from exmarine.

**Comment by emmanuelthesis** [comment]
please, can you give an example of how to use this: 
For example i want to encrypt a string: "helloworld" and get the string back after decryption.

**Comment by tilenmarc** [comment]
Hey,
you will need some library for symmetric encryption (for example libgcrypt). Based on your previous questions you want to use it together with FAME. You can think of ABE scheme as a key management scheme. What you need to do is:
- choose a random FP12_BN254 element and encrypt it with FAME
- change FP12_BN254 into a string (for example with FP12_BN254_toOctet, or with serialization that we discussed in the other discussion)
- hash that string into a 128 bit value
- use that value as a key for symmetric encryption, with which you encrypt your message
- use FAME to decide who can decrypt
- one who decrypts FP12_BN254 element the key can also change it into a string, hash it and get the key for symmetric encryption. He can decrypt the message.

**Comment by tilenmarc** [comment]
As I said, to encrypt a char *msg = "I want to encrypt and decrypt you with the key management" you need a library for symmetric cryptography. I cannot give you a code example if I don't know which library will you be using. But for example if you wil be using `libhydrogen`, you can check [this link](https://github.com/jedisct1/libhydrogen/wiki/Secret-key-encryption). Instead of creating the secret key with their function, you should create it from FP12_BN254 in a way I wrote above.

**Comment by emmanuelthesis** [comment]
Thanks for your guidance. I appreciate all your effort so far. i am sorry for giving you much stress. I reviewed the two library you sent to me. I decided to use libhydrogen. I did implement is as follows but not getting expected result. my c programming knowledge not so good. 
    cfe_ser buf4;  
    hydro_secretbox_keygen(key);
    char *MESSAGE = "Helloworld";
    size_t MESSAGE_LEN = strlen(MESSAGE);
    uint8_t ciphertext[CIPHERTEXT_LEN];
    hydro_secretbox_keygen(key);
    hydro_secretbox_encrypt(ciphertext, MESSAGE, MESSAGE_LEN, 0, CONTEXT, key);
    cfe_FP12_BN254_ser((FP12_BN254 *)ciphertext, &buf4);

and use 
    cfe_fame_encrypt(&cipher, (FP12_BN254 *)buf4.ser, &msp, &pk2, &fame);


and at the receiver end:

    error = cfe_fame_decrypt(&decryption, &cipher2, &keys, &fame);    
    if (error==0)
    {
        printf("Decryption successful \n");
        cfe_ser buf3;
        cfe_FP12_BN254_read(&decryption, &buf3);
        char decrypted[11];
        hydro_secretbox_decrypt(decrypted, buf3.ser, CIPHERTEXT_LEN, 0, CONTEXT, key);
        printf("%s", decrypted);

but not working.

**Comment by tilenmarc** [comment]
Hi,
you are not following the instructions I wrote you.  Your code has a lot of mistakes.
At the encryptor:
-take a random element, here I am taking simply one:
FP12_BN254 key1;
FP12_BN254_one(&key1);
- serialize it
cfe_ser buf;
cfe_FP12_BN254_ser(&key1, &buf);`
- use some hashing or other method to change `buf.ser` into `key` of type `uint8_t key[hydro_secretbox_KEYBYTES];` (you will need to look a bit into this, but shoudnt be too hard)
- then encrypt your message with that key (don't generate it again)
char *MESSAGE = "Helloworld";
size_t MESSAGE_LEN = strlen(MESSAGE);
uint8_t ciphertext[CIPHERTEXT_LEN];
hydro_secretbox_encrypt(ciphertext, MESSAGE, MESSAGE_LEN, 0, CONTEXT, key);
- now ciphertext is of the form uint8_t ciphertext[CIPHERTEXT_LEN];, so you do not need to serialize it, just send it
- encrypt `key1` with FAME and send it

At the decryptor:
- decrypt `key1` using fame
- use the same procedure as above to get key of type `uint8_t key[hydro_secretbox_KEYBYTES];` from `key`
- decrypt the message using that key
char decrypted[MESSAGE_LEN];
hydro_secretbox_decrypt(decrypted, ciphertext, CIPHERTEXT_LEN, 0, CONTEXT, key)

**Comment by emmanuelthesis** [comment]
Hello,
Thanks for your guidance, it works perfectly okay now.

**Comment by tilenmarc** [comment]
Great!
