### ISSUE TITLE
cfe_ddh_multi_fe_key size discrepancy

### ISSUE THREAD

**Issue by AymericGenet** [fentec-project/CiFEr#25]
Dear CiFEr team,

In [multi_ddh.c:73](../blob/master/src/innerprod/simple/ddh_multi.c#L73), the function `cfe_ddh_multi_fe_key_init(cfe_ddh_multi_fe_key *key, cfe_ddh_multi *m)` initializes `key->keys` with the size of the input vectors (i.e., ` m->scheme.l`) instead of (presumably) the number of users (i.e., `m->slots`).

As a result, if `m->slots` is greater than `m->scheme.l` and since in [multi_ddh.c:127](../blob/master/src/innerprod/simple/ddh_multi.c#L127), the function `cfe_ddh_multi_derive_fe_key(cfe_ddh_multi_fe_key *res, cfe_ddh_multi *m, cfe_ddh_multi_sec_key *msk, cfe_mat *y)` calls `cfe_vec_set(&res->keys, key, i)` from `i = 0` to `m->slots`, this can potentially cause an assertion error at [vec.c:132](../blob/master/src/data/vec.c#L132): because `i > v->size`. The same would occur in [multi_ddh.c:163](../blob/master/src/innerprod/simple/ddh_multi.c#L163) with the function `cfe_ddh_multi_decrypt(mpz_t res, cfe_ddh_multi *m, cfe_mat *ciphertext, cfe_ddh_multi_fe_key *key, cfe_mat *y)` since `cfe_vec_get(k, &key->keys, i)` is called with the same range.

Below is a minimal working example that triggers the assertion error:

```c
#include <gmp.h>
#include "cifer/data/mat.h"
#include "cifer/innerprod/simple/ddh_multi.h"

int main(void)
{
	size_t numClients = 3;
	size_t l = 2;
	mpz_t bound;
	mpz_init_set_ui(bound, 1000);

	cfe_mat Y;
	cfe_mat_init(&Y, numClients, l);

	size_t modulus_len = 64;
	cfe_ddh_multi m;
	cfe_ddh_multi_init(&m, numClients, l, modulus_len, bound);

	cfe_mat mpk;
	cfe_ddh_multi_sec_key msk;
	cfe_ddh_multi_master_keys_init(&mpk, &msk, &m);
	cfe_ddh_multi_generate_master_keys(&mpk, &msk, &m);
	cfe_ddh_multi_fe_key fe_key;
	cfe_ddh_multi_fe_key_init(&fe_key, &m);
	/* The next line will cause an assertion error */
	cfe_ddh_multi_derive_fe_key(&fe_key, &m, &msk, &Y);

	mpz_clear(bound);
	cfe_mat_frees(&Y, &mpk, NULL);
	cfe_ddh_multi_free(&m);
	cfe_ddh_multi_sec_key_free(&msk);
	cfe_ddh_multi_fe_key_free(&fe_key);

	return 0;
}
```

Best regards,
Aymeric

**Comment by tilenmarc** [comment]
Great catch, thanks. I will fix this problem as soon as possible.
Best, Tilen
