### ISSUE TITLE
About measuring communication cost

### ISSUE THREAD

**Issue by YFMao15** [fentec-project/CiFEr#34]
Hi there, I am using CiFEr to achieve a multi-party functional encryption. I took the example presented in CiFEr's cover page, and it works well. 

I am wondering how to measure the traffic cost between different parties.The code of your example just mixed the computation of all parties together. Is there a way to split the code into different pieces for encryptors and decryptor, and then measure the communication among them?

Thanks for your help in advance!

**Comment by tilenmarc** [comment]
Hi,
sorry for a late response. If you want to send ciphertexts, keys, etc. you will need to implement some kind of serialization of the structs corresponding to what you want to send. This needs some work in C. We implemented serialization for ABE schemes using [protobuf](https://github.com/protocolbuffers/protobuf) but not for FE schemes. Please see tests https://github.com/fentec-project/CiFEr/tree/master/test/serialization and implementation https://github.com/fentec-project/CiFEr/tree/master/src/serialization

**Comment by YFMao15** [comment]
Thank you for your response. I will figure out that part.

Another quick question about cmake cpp file with cifer functions:
I am writing the CmakeLists.txt like this:
add_executable(a a.cpp)
target_link_libraries(a gmp cifer)

No matter how I add -lcifer flag in CMAKE_C_FLAGS, the cifer linker does not work.  I tried adding CMAKE_EXE_LINKER_FLAGS, and target_link_libraries with cifer. But none of them work. 

Any ideas?

**Comment by YFMao15** [comment]
I found another way to compile. Close this issue for now
