### ISSUE TITLE
Addition of elements in fp12

### ISSUE THREAD

**Issue by fghartmann** [fentec-project/CiFEr#36]
Hello,

CiFEr configures amcl with BN254. The BN254 internally uses fp12 to represent points. 
For some implementation we need addition in fp12 which is unfortunately not implemented 
in the amcl library. Is there a reason why this is not in general possible.

Aside
Do you know of any pairing friendly curve where addition of curve elements is possible ?

**Comment by fghartmann** [comment]
We resolved the issue. We didn't need addition after all.

**Comment by tilenmarc** [comment]
Sorry that we did not respond sooner, we were out of office. Great that you resolved it, without needing the addition. Otherwise, you would probably need to implement it yourself, which could be a bit annoying to do, but not out of reach.
